#
# This is the server logic of a Shiny web application. You can run the
# application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)

shinyServer(function(input, output) {
    
    getData <- reactive({
        n <- ifelse(input$numPoints >= 20, input$numPoints, 20)
        n1 <- n / 3; n2 <- n1; n3 <- n - n1 - n2
        dataX <- c(rnorm(n1, mean = 1, sd = 0.5),
                   rnorm(n2, mean = 1, sd = 0.3),
                   rnorm(n3, mean = 3, sd = 0.3))
        dataY <- c(rnorm(n1, mean = 1, sd = 0.5),
                   rnorm(n2, mean = 3, sd = 0.3),
                   rnorm(n3, mean = 1, sd = 0.3))
        data.frame(dataX = dataX, dataY = dataY)
    })

    output$plot1 <- renderPlot({
        df <- getData()
        if(input$showClusters) {
            set.seed(42)
            nc <- ifelse(input$numClusters > 0, input$numClusters, 1)
            cl <- kmeans(df, centers = ifelse(nc <= 10, nc, 10))
            pt_colors <- cl$cluster
        } else {
            pt_colors <- "grey"
        }
        plot(df$dataX, df$dataY, xlab = "x", ylab = "y", main = "Plot of Random Points",
             xlim = c(-1, 5), ylim = c(-1, 5), col = pt_colors)
    })

    output$help <- renderUI(HTML("This app shows the clusters created by the k-means algorithm for a simple 2D dataset. <br/>
                                  The number of points (between 20 and 1000) can be chosen by the user. The points are
                                  generated by 3 normal distributions with different centers. <br/>
                                  The user can vary the number of clusters computed by the k-means algorithm (between 1 and 10). <br/>
                                  The box 'Show clusters' displays the clusters in different colors."))
})
